"use client"

import { useEffect, useState } from "react"
import { apiFetch } from "@/lib/api"
import { toast } from "sonner"

type Limit = { productId: string; minPrice: number; product?: { name: string; sku: string; wholesalePrice: number } }
type Product = { _id: string; name: string; sku: string; wholesalePrice: number }
export default function NegotiationSettingsPage() {
  const [limits, setLimits] = useState<Limit[]>([]); const [products, setProducts] = useState<Product[]>([]); const [productId, setProductId] = useState(""); const [minPrice, setMinPrice] = useState("")
  async function load() { try { const [limitsRes, productsRes] = await Promise.all([apiFetch("/admin/negotiation-limits"), apiFetch("/admin/products?limit=100")]); const limitsData = await limitsRes.json(); const productsData = await productsRes.json(); if (!limitsRes.ok || !productsRes.ok) throw new Error(limitsData.message || productsData.message); setLimits(limitsData.data || []); setProducts(productsData.data || []) } catch (error: any) { toast.error(error.message || "Failed to load negotiation settings") } }
  useEffect(() => { load() }, [])
  async function save() { if (!productId || minPrice === "") return; try { const res = await apiFetch(`/admin/negotiation-limits/${productId}`, { method: "PUT", body: JSON.stringify({ minPrice: Number(minPrice) }) }); const data = await res.json(); if (!res.ok) throw new Error(data.message); toast.success("Staff minimum price saved"); setProductId(""); setMinPrice(""); load() } catch (error: any) { toast.error(error.message || "Unable to save limit") } }
  async function remove(id: string) { try { const res = await apiFetch(`/admin/negotiation-limits/${id}`, { method: "DELETE" }); const data = await res.json(); if (!res.ok) throw new Error(data.message); toast.success("Staff price limit removed"); load() } catch (error: any) { toast.error(error.message || "Unable to remove limit") } }
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Negotiation Settings</h1><p className="text-sm text-slate-500">Set the minimum price that staff may accept or offer for each product.</p></div><div className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-[1fr_220px_auto]"><select className="rounded border p-2" value={productId} onChange={(e) => setProductId(e.target.value)}><option value="">Choose product</option>{products.map((product) => <option key={product._id} value={product._id}>{product.name} ({product.sku})</option>)}</select><input className="rounded border p-2" type="number" min="0" placeholder="Minimum ₹/unit" value={minPrice} onChange={(e) => setMinPrice(e.target.value)}/><button onClick={save} className="rounded bg-emerald-600 px-4 py-2 font-semibold text-white">Save limit</button></div><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Product</th><th>SKU</th><th>Staff minimum</th><th className="p-3">Action</th></tr></thead><tbody>{limits.map((limit) => <tr key={limit.productId} className="border-t"><td className="p-3 font-semibold">{limit.product?.name || limit.productId}</td><td>{limit.product?.sku || "—"}</td><td>₹{limit.minPrice}/unit</td><td className="p-3"><button onClick={() => remove(limit.productId)} className="rounded border border-rose-200 px-2 py-1 text-rose-700">Remove</button></td></tr>)}</tbody></table></div></div>
}
